[package]
name = "rustytestend"
version = "0.0.5"
authors = ["Vadim Palatov <vatrandero@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde = {version =  "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
sqlx = {version = "0.8.2", features = ["runtime-tokio","postgres", "tls-native-tls" ]}
tokio = {version = "1.41.1", default-features = false, features = ["net", "fs"]}
toml = "0.8.19"
uuid = "1.11.0"
warp = "0.3.7"
