[package]
name = "rustytestend"
version = "0.0.8"
authors = ["Vadim Palatov <vatrandero@gmail.com>"]
license = "MIT"
edition = "2021"
[dependencies]
async-trait = "0.1.83"
chrono = "0.4.38"
log = "0.4.22"
once_cell = "1.20.2"
pretty_env_logger = "0.5.0"
serde = {version =  "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
sqlx = {version = "0.8.2", features = ["runtime-tokio","postgres", "tls-native-tls" ]}
tokio = {version = "1.41.1", default-features = false, features = ["net", "fs"]}
toml = "0.8.19"
uuid = "1.11.0"
warp = "0.3.7"
warp-sessions = "1.0.19"
