

-- NOT FINAL VERSION.
-- UNTIL LATE STAGES OF DEVELOPMENT OR RELEASE - MAY BE OVERWRITTEN.
-- AFTER - CREATE NEW MIGRATION SCRIPTS.
DROP TABLE answers CASCADE;
DROP TABLE questions CASCADE;
DROP TABLE questions_answers_rels;
DROP TABLE user_sessions CASCADE;
DROP TABLE test_asignments CASCADE;
DROP TABLE tests_journal CASCADE;
DROP TABLE test_sessions CASCADE;
DROP TABLE tests CASCADE;
DROP TABLE users CASCADE;
DROP TYPE IF EXISTS user_role;