-- NOT FINAL VERSION.
-- UNTIL LATE STAGES OF DEVELOPMENT OR RELEASE - MAY BE OVERWRITTEN.
-- AFTER - CREATE NEW MIGRATION SCRIPTS.
-- IF THIS COMMENT REMOOVED - IT MEANS "DO NOT EDIT ANYMORE"


DROP TRIGGER IF EXISTS trg_check_expired_or_blocked ON test_session_answered_rels;
DROP FUNCTION IF EXISTS chk_record_expired_or_locked;